//Zelda 64 Dawn & Dusk - Expansion Disk
//By LuigiBlood

//Uses ARM9 bass

//DMA Data equivalent
constant EZLJ_FILE_COUNT(1)

EZLJ_FILE_TABLE0:
n64dd_FileEntry(VFILE_MAP_GRAND_STATIC, 0x00967000, EZLJ_MAP_GRAND_STATIC)
EZLJ_FILE_TABLE0_END:
scope EZLJ_FILE_TABLE0 {
    variable size(EZLJ_FILE_TABLE0_END - EZLJ_FILE_TABLE0)
}

EZLJ_FILE_TABLE1:
n64dd_FileEntry(VFILE_MAP_GRAND_STATIC, 0x00967000, EZLJ_MAP_GRAND_STATIC)
EZLJ_FILE_TABLE1_END:
scope EZLJ_FILE_TABLE1 {
    variable size(EZLJ_FILE_TABLE1_END - EZLJ_FILE_TABLE1)
}

EZLJ_FILE_TABLE2:
n64dd_FileEntry(VFILE_MAP_GRAND_STATIC, 0x00967000, EZLJ_MAP_GRAND_STATIC)
EZLJ_FILE_TABLE2_END:
scope EZLJ_FILE_TABLE2 {
    variable size(EZLJ_FILE_TABLE2_END - EZLJ_FILE_TABLE2)
}