//Zelda Expansion Disk
//By LuigiBlood

//Uses ARM9 bass

//RAM Usage

constant DDHOOK_PATCH(0x80700000)	//PATCH
constant DDHOOK_RAM(0x80410000)		//CODE
constant DDHOOK_GPRAM(0x80420000)	//GENERAL PURPOSE
	constant DDHOOK_ADDRTABLE(DDHOOK_GPRAM+0)			//ADDRESS TABLE
	constant DDHOOK_VERSION(DDHOOK_GPRAM+4)				//VERSION DETECT
	constant DDHOOK_VERSIONTABLE(DDHOOK_GPRAM+8)		//VERSION SPECIFIC TABLE

	constant DDHOOK_TEXTTABLE(DDHOOK_GPRAM+0x10000)		//ENGLISH TEXT TABLE (DDHOOK_MESSAGETABLENES)
	constant DDHOOK_TEXTDATA(DDHOOK_GPRAM+0x20000)		//ENGLISH TEXT DATA (DDHOOK_NESTEST)

	constant DDHOOK_AUDIO_TABLES(DDHOOK_GPRAM+0x59000)	//AUDIO TABLES
		constant DDHOOK_AUDIOBANK_TABLE(DDHOOK_AUDIO_TABLES)
		constant DDHOOK_AUDIOINST_TABLE(DDHOOK_AUDIOBANK_TABLE+EZLJ_AUDIOBANK_TABLE.size)
		constant DDHOOK_AUDIOSEQ_TABLE(DDHOOK_AUDIOINST_TABLE+EZLJ_AUDIOINST_TABLE.size)

	constant DDHOOK_AUDIOBANK(DDHOOK_AUDIOSEQ_TABLE+EZLJ_AUDIOSEQ_TABLE.size)		//AUDIOBANK
	constant DDHOOK_AUDIOSEQ(DDHOOK_AUDIOBANK+EZLJ_AUDIOBANK0.size)					//AUDIOSEQ

	constant DDHOOK_SCENETITLECARD(DDHOOK_AUDIOSEQ+EZLJ_AUDIOSEQ.size)				//TITLE CARD TEXTURE (0x1B00)
	constant DDHOOK_VFILETABLE(DDHOOK_SCENETITLECARD+0x1B00)						//VFILE TABLE
	constant DDHOOK_OVL_PLAYER_ACTOR(DDHOOK_VFILETABLE+(EZLJ_FILE_COUNT*0x10))		//OVL_PLAYER_ACTOR
	constant DDHOOK_OVL_EFFECT_SS_STICK(DDHOOK_OVL_PLAYER_ACTOR+0x26560)			//OVL_EFFECT_SS_STICK
	constant DDHOOK_OVL_ITEM_SHIELD(DDHOOK_OVL_EFFECT_SS_STICK+0x3A0)				//OVL_ITEM_SHIELD