//Zelda Expansion Disk
//By LuigiBlood

//Uses ARM9 bass

//RAM Usage
n64dd_RamSetAddress(0x80410000)
n64dd_RamDefine(DDHOOK_RAM, 0x10000)		//MAIN DISK CODE

n64dd_RamSetAddress(0x80420000)
n64dd_RamDefine(DDHOOK_GPRAM, 0)
	n64dd_RamDefine(DDHOOK_ADDRTABLE, 4)				//n64dd Function Table Pointer
	n64dd_RamDefine(DDHOOK_VERSION, 4)					//VERSION
	n64dd_RamDefine(DDHOOK_VERSIONTABLE, 8)				//VERSION SPECIFIC DATA

	n64dd_RamDefine(DDHOOK_TEXTTABLE, 0x10000)		//MESSAGE TABLE
	n64dd_RamDefine(DDHOOK_TEXTDATA, 0x39000)		//MESSAGE STATIC DATA

	n64dd_RamDefine(DDHOOK_AUDIOBANK_TABLE, EZLJ_AUDIOBANK_TABLE.size)	//AUDIOBANK_TABLE
	n64dd_RamDefine(DDHOOK_AUDIOINST_TABLE, EZLJ_AUDIOINST_TABLE.size)	//AUDIOINST_TABLE
	n64dd_RamDefine(DDHOOK_AUDIOSEQ_TABLE, EZLJ_AUDIOSEQ_TABLE.size)	//AUDIOSEQ_TABLE

	n64dd_RamDefine(DDHOOK_AUDIOBANK, EZLJ_AUDIOBANK0.size)				//AUDIOBANK
	n64dd_RamDefine(DDHOOK_AUDIOSEQ, EZLJ_AUDIOSEQ.size)				//AUDIOSEQ

	n64dd_RamDefine(DDHOOK_SCENETITLECARD, 0x1B00)						//SCENE TITLE CARD TEXTURE
	n64dd_RamDefine(DDHOOK_VFILETABLE, (EZLJ_FILE_COUNT*0x10))

	//Overlays
	n64dd_RamDefine(DDHOOK_OVL_PLAYER_ACTOR, 0x26560)
	n64dd_RamDefine(DDHOOK_OVL_KALEIDO_SCOPE, 0x1C990)
	n64dd_RamDefine(DDHOOK_OVL_EFFECT_SS_STICK, 0x3A0)
	n64dd_RamDefine(DDHOOK_OVL_ITEM_SHIELD, 0xA10)

	//Objects
	n64dd_RamDefine(DDHOOK_GAMEPLAY_DANGEON_KEEP, EZLJ_GAMEPLAY_DANGEON_KEEP.size)
	n64dd_RamDefine(DDHOOK_OBJECT_LINK_CHILD, EZLJ_OBJECT_LINK_CHILD.size)

	//Static
	n64dd_RamDefine(DDHOOK_ICON_ITEM_FIELD_STATIC, EZLJ_ICON_ITEM_FIELD_STATIC.size)
	n64dd_RamDefine(DDHOOK_ICON_ITEM_NES_STATIC, EZLJ_ICON_ITEM_NES_STATIC.size)

	//Scene Room Buffers
	n64dd_RamDefine(DDHOOK_SCENE_ROOM_TABLE, 0x80)
	n64dd_RamDefine(DDHOOK_SCENE_ROOM_DATA, 0x18620)

n64dd_RamSetAddress(0x80700000)
	n64dd_RamDefine(DDHOOK_PATCH, 0x100000)
